exclude: |
  ^context_portal/alembic/versions/|  # Skip database migration files
  ^node_modules/|                     # Skip JavaScript dependencies
  ^.venv/                            # Skip Python virtual environment

repos:
  # Basic file hygiene and validation
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace      # Remove trailing spaces at end of lines
      - id: end-of-file-fixer       # Ensure files end with newline
      - id: check-yaml              # Validate YAML syntax
      - id: check-json              # Validate JSON syntax
      - id: check-toml              # Validate TOML syntax (pyproject.toml, etc.)
      - id: check-added-large-files # Prevent accidentally committing large files
      - id: check-merge-conflict    # Detect Git merge conflict markers
      - id: debug-statements        # Catch forgotten print(), pdb, etc.

  # Import organization - sorts and groups imports consistently
  - repo: https://github.com/pycqa/isort
    rev: 7.0.0
    hooks:
      - id: isort
        args: ["--profile", "black"]  # Make isort compatible with Black formatting

  # Code formatting - enforces consistent style (line length, quotes, etc.)
  - repo: https://github.com/psf/black
    rev: 25.9.0
    hooks:
      - id: black

  # Fast linting - checks code quality, style violations, potential bugs
  # Replaces flake8, pylint, and many other tools with better performance
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.0
    hooks:
      - id: ruff
        args:
          - "--fix"                              # Auto-fix issues when possible
          - "--line-length=88"                   # Match Black's line length
          - "--extend-ignore=E203,E501,E221,E231"  # Ignore specific rules that conflict with Black

# Static type checking - catches type-related errors before runtime
  # Helps find attribute errors, wrong argument types, etc.
  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.406
    hooks:
      - id: pyright
        additional_dependencies:
          - pyright==1.1.406
          - loguru
          - mcp>=1.16.0
          - httpx>=0.28.1
          - pyyaml>=6.0.0
          - rich
          - sqlalchemy
          - alembic
